<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DKIJakarta;
use Illuminate\Support\Facades\Hash;

class DummySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DKIJakarta::insert([
        [
            "id"            => '89815',
            "nkk"           => '3101010501090934',
            "nik"           => '3101010608010001',
            "nama"          => 'LUTPI HERMAWAN',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '06|08|2001',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89817',
            "nkk"           => '3101010501091399',
            "nik"           => '3101016505010002',
            "nama"          => 'MARYANA',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '25|05|2001',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'masyarakat',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89818',
            "nkk"           => '3101010501091149',
            "nik"           => '3101010202010001',
            "nama"          => 'ADE GUNAWAN',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '02|02|2001',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89819',
            "nkk"           => '3101010501091018',
            "nik"           => '3101011401010002',
            "nama"          => 'BURHANUDIN',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '14|01|2001',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89820',
            "nkk"           => '3101010501090823',
            "nik"           => '3101011012000001',
            "nama"          => 'AHMAD GUNAWAN',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '10|12|2000',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89821',
            "nkk"           => '3101010501091982',
            "nik"           => '3101017009000001',
            "nama"          => 'PUTRI REGITA CAHYANI',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '30|09|2000',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89822',
            "nkk"           => '3101010501090962',
            "nik"           => '3101012609000001',
            "nama"          => 'RIFQI',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '26|09|2000',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89823',
            "nkk"           => '3101010501092300',
            "nik"           => '3101012108000001',
            "nama"          => 'ABDUL GOPUR',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '21|08|2000',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '006',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89824',
            "nkk"           => '3101010501091031',
            "nik"           => '3101015107000001',
            "nama"          => 'CUSNENI',
            "tempat_lahir"  => 'JABAR',
            "tgl_lahir"     => '11|07|2000',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89825',
            "nkk"           => '3101010501091419',
            "nik"           => '3101011806000001',
            "nama"          => 'IRWAN GUNAWAN',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '18|06|2000',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89826',
            "nkk"           => '3101010501092302',
            "nik"           => '3101011104000002',
            "nama"          => 'RIZKY SUHENDRA',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '11|04|2000',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89828',
            "nkk"           => '3101010501090944',
            "nik"           => '3101014401000001',
            "nama"          => 'AWALIAH RISTIANA',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '04|01|2000',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89829',
            "nkk"           => '3101010501091096',
            "nik"           => '3101011012990001',
            "nama"          => 'IKROMULLAH',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '10|12|1999',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '006',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89830',
            "nkk"           => '3101010501090066',
            "nik"           => '3101010909991001',
            "nama"          => 'DEDI SUHENDRA',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '09|09|1999',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89831',
            "nkk"           => '3101010501090963',
            "nik"           => '3101014108990003',
            "nama"          => 'GUSTIANI WULAN SARI',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '01|08|1999',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89832',
            "nkk"           => '3101012709121005',
            "nik"           => '3101013006990002',
            "nama"          => 'M. AANG KUNAEFI',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '30|06|1999',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89833',
            "nkk"           => '3101010501091194',
            "nik"           => '3101011201990001',
            "nama"          => 'FAUKI MUKODAM',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '12|01|1999',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89834',
            "nkk"           => '3101010501091561',
            "nik"           => '3101015412980001',
            "nama"          => 'RENA SUPRIATI',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '14|12|1998',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89835',
            "nkk"           => '3101010501090973',
            "nik"           => '3101012007980002',
            "nama"          => 'KHAIDIR SAIFUL',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '20|07|1998',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89836',
            "nkk"           => '3101010501091164',
            "nik"           => '3101012806980001',
            "nama"          => 'SOPIAN HIDAYAT',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '28|06|1998',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '006',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89837',
            "nkk"           => '3101010501092402',
            "nik"           => '3101010101980001',
            "nama"          => 'AL IMBRON',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '01|01|1998',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89838',
            "nkk"           => '3101010501091570',
            "nik"           => '3101011511970002',
            "nama"          => 'HABIB SYEHAN',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '15|11|1997',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '006',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89839',
            "nkk"           => '3101010501091105',
            "nik"           => '3101011111970002',
            "nama"          => 'SUHEFANUDIN',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '12|11|1997',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89840',
            "nkk"           => '3101010501091224',
            "nik"           => '3101016410970001',
            "nama"          => 'INTAN OKTAVIANI',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '24|10|1997',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89841',
            "nkk"           => '3101010501090863',
            "nik"           => '3101011010970001',
            "nama"          => 'JUMHARIYANTO',
            "tempat_lahir"  => 'TANGERANG',
            "tgl_lahir"     => '10|10|1997',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89842',
            "nkk"           => '3101010501090831',
            "nik"           => '3101011109970001',
            "nama"          => 'AHMAD SUHIYAN',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '11|09|1997',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89843',
            "nkk"           => '3101010501090988',
            "nik"           => '3101010701970001',
            "nama"          => 'CHPY HERMAWANSAH',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '07|01|1997',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89844',
            "nkk"           => '3101010501090995',
            "nik"           => '3101010501970002',
            "nama"          => 'ARI GUNAWAN',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '05|01|1997',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89845',
            "nkk"           => '3101010501092582',
            "nik"           => '3101014112960001',
            "nama"          => 'IFTA ELINDA',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '01|12|1996',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '006',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89846',
            "nkk"           => '3101010501091105',
            "nik"           => '3101016510960001',
            "nama"          => 'SITI AMELIA',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '25|10|1996',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89847',
            "nkk"           => '3101010501090947',
            "nik"           => '3101011408960001',
            "nama"          => 'GUSTOMI',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '14|08|1996',
            "kawin"         => 'B',
            "jenis_kelamin" => 'L',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89848',
            "nkk"           => '3101011911121001',
            "nik"           => '3101014407960004',
            "nama"          => 'ANGGRAENI SAFITRI',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '04|07|1996',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '007',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG',
        ],
        [    
            "id"            => '89849',
            "nkk"           => '3101010501092202',
            "nik"           => '3101014305960001',
            "nama"          => 'KHOIRUN NISA',
            "tempat_lahir"  => 'JAKARTA',
            "tgl_lahir"     => '03|05|1996',
            "kawin"         => 'B',
            "jenis_kelamin" => 'P',
            "alamat"        => 'PULAU PANGGANG',
            "rt"            => '006',
            "rw"            => '003',
            "difabel"       => '0',
            "keterangan"    => '0',
            "sumberdata"    => 'coklit',
            "tps"           => '001',
            "kel_id"        => '25826',
            "kd_pro"        => '31',
            "pro"           => 'DKI JAKARTA',
            "kd_kab"        => '3101',
            "kab"           => 'KEPULAUAN SERIBU',
            "kd_kec"        => '310101',
            "kec"           => 'KEPULAUAN SERIBU UTARA',
            "kel"           => 'PULAU PANGGANG'
        ]]);
    }
}


